import bcrypt from "bcryptjs";
import { User } from "./models/userModel";
import { Product } from "./models/productModel";

export const sampleProducts: Product[] = [
  {
    name: "Gucci Vintage Dress",
    slug: "gucci-vintage-dress",
    category: "Dresses",
    image: "/images/p1.jpg", // 579 x 829px
    price: 120,
    countInStock: 5,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 40,
    description: "Gucci dress from 1998 runway, only 5 in stock worldwide ",
  },
  {
    name: "Prada Vintage Pants",
    slug: "prada-vintage-pants",
    category: "pants",
    image: "/images/p2.jpg",
    price: 250,
    countInStock: 10,
    brand: "Prada",
    rating: 4.3,
    numReviews: 55,
    description: "Prada Vintage pants",
  },
  {
    name: "Dior Sunglasses",
    slug: "dior-sunglasses",
    category: "sunglasses",
    image: "/images/p3.jpg",
    price: 233,
    countInStock: 40,
    brand: "Dior",
    rating: 4.0,
    numReviews: 88,
    description: "Dior Sunglasses, 2000 year edition",
  },
  {
    name: "LV Vintage Bag ",
    slug: "lv-vintage-bag",
    category: "Bags",
    image: "/images/p4.jpg",
    price: 800,
    countInStock: 1,
    brand: "Lui Vuitton",
    rating: 5.0,
    numReviews: 4,
    description: "Lui Vuitton Vintage Bag From 90-ies",
  },
  {
    name: "Burberry bag",
    slug: "burberry-bag",
    category: "Bags",
    image: "/images/p5.jpg",
    price: 777,
    countInStock: 1,
    brand: "Burberry",
    rating: 5.0,
    numReviews: 4,
    description: "Burrbery bag from 1990 collection in a good condition",
  },
  {
    name: "Balenciaga Shoes",
    slug: "balenciaga-shoes",
    category: "shoes",
    image: "/images/p6.jpg",
    price: 555,
    countInStock: 5,
    brand: "Balenciaga",
    rating: 4.8,
    numReviews: 40,
    description: "Balenciaga Sneackers in a good condition ",
  },
  {
    name: "Fendi Bag",
    slug: "fendi-bag",
    category: "Bags",
    image: "/images/p7.jpg",
    price: 780,
    countInStock: 1,
    brand: "Fendi",
    rating: 5.0,
    numReviews: 1,
    description: "Fendi Baguette Bag in a very good condition  ",
  },

  {
    name: "Balenciaga Hat ",
    slug: "balenciaga-hat",
    category: "hats",
    image: "/images/p8.jpg",
    price: 190,
    countInStock: 8,
    brand: "Balenciaga",
    rating: 4.5,
    numReviews: 5,
    description: "Balenciaga Hat looking in a good condition ",
  },
  {
    name: "Versace Dress",
    slug: "versace-dress",
    category: "Dresses",
    image: "/images/p9.jpg",
    price: 907,
    countInStock: 1,
    brand: "Versace",
    rating: 5.0,
    numReviews: 1,
    description: "Unworn Versace Vintage Dress",
  },
  {
    name: "Dior Heels",
    slug: "dior-heels",
    category: "Heels",
    image: "/images/p10.jpg",
    price: 790,
    countInStock: 5,
    brand: "Dior",
    rating: 4.5,
    numReviews: 33,
    description: "Dior heels in a very good condition, rarelly worn ",
  },
  {
    name: "Fendi Heels",
    slug: "fendi-heels",
    category: "heels",
    image: "/images/p11.jpg",
    price: 690,
    countInStock: 4,
    brand: "Fendi",
    rating: 4.5,
    numReviews: 2,
    description:
      "Fendi vintage heels from 90-ies, only worn twice, in a very good condition ",
  },
  {
    name: "Gucci sunglasses",
    slug: "gucci-sunglasses",
    category: "sunglasses",
    image: "/images/p12.jpg",
    price: 300,
    countInStock: 5,
    brand: "Gucci",
    rating: 4.5,
    numReviews: 30,
    description: "Gucci vintage sunglasses",
  },
  {
    name: "Prada Bag",
    slug: "prada-bag",
    category: "Bags",
    image: "/images/p13.jpg",
    price: 709,
    countInStock: 9,
    brand: "Prada",
    rating: 4.5,
    numReviews: 11,
    description: "Prada Bag in a good condition, like a new  ",
  },
  {
    name: "Bottega Veneta Bag",
    slug: "bottegga-venetta-bag",
    category: "Bags",
    image: "/images/p14.jpg",
    price: 790,
    countInStock: 7,
    brand: "Bottega Veneta",
    rating: 4.9,
    numReviews: 7,
    description: "Bottega Veneta Bag, brand new, never worn",
  },
  {
    name: "Dior Dress",
    slug: "dior-dress",
    category: "Dresses",
    image: "/images/p15.jpg",
    price: 690,
    countInStock: 1,
    brand: "Dior",
    rating: 5.0,
    numReviews: 5,
    description:
      "Dior Dress from the 90-ies, in a very good condition, worn only once ",
  },
  {
    name: "Bottega Venneta Bag",
    slug: "bottega-bag",
    category: "Bags",
    image: "/images/p16.jpg",
    price: 590,
    countInStock: 6,
    brand: "Bottega Venneta",
    rating: 5.0,
    numReviews: 5,
    description: "Bottega Venneta Vintage Big Bag",
  },
  {
    name: "Salvatore Ferragamo Bag",
    slug: "ferragamo-bag",
    category: "Bags",
    image: "/images/p17.jpg",
    price: 990,
    countInStock: 8,
    brand: "Salvatore Ferragamo",
    rating: 5.0,
    numReviews: 14,
    description: "Salvatore Ferragamo Bag",
  },
  {
    name: "Dior Bag",
    slug: "dior-Bag",
    category: "Bags",
    image: "/images/p18.jpg",
    price: 990,
    countInStock: 8,
    brand: "Dior",
    rating: 5.0,
    numReviews: 5,
    description: "Dior Bag from the 90-ies, Brand new with tags",
  },
  {
    name: "YSL Bag",
    slug: "ysl-bag",
    category: "Bags",
    image: "/images/p19.jpg",
    price: 590,
    countInStock: 5,
    brand: "YSL",
    rating: 5.0,
    numReviews: 5,
    description: "YSL Bag Brand New",
  },
  {
    name: "Prada Heels",
    slug: "prada-heels",
    category: "Bags",
    image: "/images/p20.jpg",
    price: 790,
    countInStock: 6,
    brand: "Prada",
    rating: 5.0,
    numReviews: 8,
    description: "Prada Heels",
  },
  {
    name: "Chanell Heels",
    slug: "chanel-heels",
    category: "Chanel",
    image: "/images/p21.jpg",
    price: 990,
    countInStock: 5,
    brand: "Chanel",
    rating: 5.0,
    numReviews: 5,
    description: "Chanel Heels Brand new",
  },
  {
    name: "Gucci Heels",
    slug: "gucci-heels",
    category: "Heels",
    image: "/images/p22.jpg",
    price: 890,
    countInStock: 8,
    brand: "Gucci",
    rating: 5.0,
    numReviews: 5,
    description: "Gucci Heels Brand New",
  },
  {
    name: "Dior Dress",
    slug: "dior-dress",
    category: "Dresses",
    image: "/images/p23.jpg",
    price: 990,
    countInStock: 5,
    brand: "Dior",
    rating: 5.0,
    numReviews: 5,
    description:
      "Dior Dress from the 90-ies, in a very good condition, worn only once ",
  },
  {
    name: "Versace Dress",
    slug: "versace-dress",
    category: "Dresses",
    image: "/images/p24.jpg",
    price: 490,
    countInStock: 5,
    brand: "Dior",
    rating: 5.0,
    numReviews: 5,
    description: "Versace Dress from the 90-ies",
  },
  {
    name: "LV Bag",
    slug: "lv-bag",
    category: "Bags",
    image: "/images/p25.jpg",
    price: 890,
    countInStock: 5,
    brand: "LV",
    rating: 5.0,
    numReviews: 5,
    description: "LV Vintage Bag Set",
  },
  {
    name: "Dior Sunglasses",
    slug: "dior-sunglasses",
    category: "Sunglasses",
    image: "/images/p26.jpg",
    price: 290,
    countInStock: 5,
    brand: "Dior",
    rating: 5.0,
    numReviews: 5,
    description: "Dior Sunglasses from the 90-ies",
  },
];

export const sampleUsers: User[] = [
  {
    name: "Joe",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456"),
    isAdmin: true,
  },
  {
    name: "John",
    email: "user@example.com",
    password: bcrypt.hashSync("123456"),
    isAdmin: false,
  },
];
